import { Request, Response } from 'express';

import { encrypt } from '../utils/crypto';

interface ConnectRepoRequestBody {
  repoUrl: string;
  authType: 'github_oauth' | string;
  authToken: string;
  branch: string;
}

export const connectRepo = async (req: Request, res: Response) => {
  const { repoUrl, authType, authToken, branch } = req.body as ConnectRepoRequestBody;

  if (!repoUrl || !authType || !authToken || !branch) {
    return res.status(400).json({ message: 'Missing required fields in request body' });
  }

  try {
    const encryptedToken = encrypt(authToken);

    // TODO: Save the repo details and encrypted token to Firestore
    // For now, we'll just log it for demonstration
    console.log('Encrypted Token:', encryptedToken);
    console.log(`Repo registered: ${repoUrl} on branch ${branch}`);

    // In a real implementation, the repoId would be generated by Firestore
    const repoId = 'unique-id-from-firestore';

    res.status(200).json({ repoId, status: 'Registered' });
  } catch (error) {
    console.error('Error connecting repo:', error);
    res.status(500).json({ message: 'Failed to connect repository' });
  }
};
